
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Nov 18 10:42:50 CST 2019
//----------------------------------------------------

package principal;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int REXTEND = 34;
  public static final int COMPARADOR = 43;
  public static final int MODULACION = 41;
  public static final int RBOLEANO = 3;
  public static final int RPUBLO = 27;
  public static final int EXPONENTE = 40;
  public static final int RTRUE = 12;
  public static final int RNULO = 15;
  public static final int RENTONCES = 9;
  public static final int ENTERO = 61;
  public static final int DIFERENTE = 44;
  public static final int RHACER = 19;
  public static final int CORCHETEC = 58;
  public static final int RESTA = 37;
  public static final int RINCLUIR = 6;
  public static final int CORCHETEA = 57;
  public static final int PUNTOCOMA = 54;
  public static final int RREAL = 4;
  public static final int RFALSE = 11;
  public static final int PARENTESISC = 56;
  public static final int PARENTESISA = 55;
  public static final int RPROP = 22;
  public static final int AND = 50;
  public static final int MENORIGUAL = 45;
  public static final int RMIENTRAS = 16;
  public static final int RPRINCIPAL = 30;
  public static final int RESCRIBIR = 20;
  public static final int RPUBA = 24;
  public static final int RMET = 23;
  public static final int OR = 51;
  public static final int RENTERO = 5;
  public static final int RISNTAN = 66;
  public static final int RDECREMENTAR = 18;
  public static final int SUMA = 36;
  public static final int LOOP = 65;
  public static final int RELIM = 32;
  public static final int RINCREMENTAR = 17;
  public static final int RCONSTRUC = 67;
  public static final int MAYORIGUAL = 46;
  public static final int EOF = 0;
  public static final int RDESDE = 14;
  public static final int error = 1;
  public static final int COMA = 59;
  public static final int CADENA = 60;
  public static final int MENOR = 48;
  public static final int RARG = 35;
  public static final int PUNTOPUNTO = 53;
  public static final int RSI = 7;
  public static final int REAL = 62;
  public static final int MAYOR = 47;
  public static final int INTERROGANTE = 49;
  public static final int RPROTO = 29;
  public static final int PUNTO = 52;
  public static final int RPRIVO = 28;
  public static final int RCADENA = 2;
  public static final int IGUALADOR = 42;
  public static final int IDCLASE = 64;
  public static final int RRETORNAR = 10;
  public static final int RINSTAN = 31;
  public static final int RPROTA = 26;
  public static final int RCLASE = 21;
  public static final int RCONSTRUCT = 33;
  public static final int RPRIVA = 25;
  public static final int RSINO = 8;
  public static final int IDVAR = 63;
  public static final int DIVISION = 39;
  public static final int RPARACADA = 13;
  public static final int MULTIPLICACION = 38;
}

